/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/notes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.notes.id"];
          created_at?: parameters["rowFilter.notes.created_at"];
          updated_at?: parameters["rowFilter.notes.updated_at"];
          title?: parameters["rowFilter.notes.title"];
          body?: parameters["rowFilter.notes.body"];
          user_id?: parameters["rowFilter.notes.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["notes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** notes */
          notes?: definitions["notes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.notes.id"];
          created_at?: parameters["rowFilter.notes.created_at"];
          updated_at?: parameters["rowFilter.notes.updated_at"];
          title?: parameters["rowFilter.notes.title"];
          body?: parameters["rowFilter.notes.body"];
          user_id?: parameters["rowFilter.notes.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.notes.id"];
          created_at?: parameters["rowFilter.notes.created_at"];
          updated_at?: parameters["rowFilter.notes.updated_at"];
          title?: parameters["rowFilter.notes.title"];
          body?: parameters["rowFilter.notes.body"];
          user_id?: parameters["rowFilter.notes.user_id"];
        };
        body: {
          /** notes */
          notes?: definitions["notes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  notes: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    body?: string;
    /** Format: uuid */
    user_id?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description notes */
  "body.notes": definitions["notes"];
  /** Format: uuid */
  "rowFilter.notes.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.notes.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.notes.updated_at": string;
  /** Format: text */
  "rowFilter.notes.title": string;
  /** Format: text */
  "rowFilter.notes.body": string;
  /** Format: uuid */
  "rowFilter.notes.user_id": string;
}

export interface operations {}

export interface external {}
